In [1]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
np.random.rand(2,3)

array([[0.2630619 , 0.97029406, 0.72487866],
       [0.28569623, 0.51447865, 0.05745564]])

In [9]:
arr2 = np.arange(16)
arr2.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
arr2.reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [16]:
arr2.shape

(16,)

In [22]:
arr2.astype(float) # 타입 변경

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [25]:
arr2.astype(int)
arr2[5:8]

array([5, 6, 7])

In [26]:
arr2[6:8] = [200, 201]

In [27]:
arr2 = np.arange(16).reshape(4,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
arr2[1,2]
arr2[1][2]    # 두개 동일

6

In [32]:
arr = np.array([90,80,70,65,85,95,90,80,75,80])
arr

array([90, 80, 70, 65, 85, 95, 90, 80, 75, 80])

In [33]:
arr >= 90

array([ True, False, False, False, False,  True,  True, False, False,
       False])

In [34]:
arr[arr>=90]

array([90, 95, 90])

In [35]:
list = [1,2,3,4]
list *2

[1, 2, 3, 4, 1, 2, 3, 4]

In [36]:
ex = np.array([1,2,3,4])
ex *2

array([2, 4, 6, 8])

In [37]:
np.square(ex)

array([ 1,  4,  9, 16], dtype=int32)

In [38]:
np.sqrt(ex)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [39]:
np.exp(ex)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [40]:
np.log(ex)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [43]:
np.add(ex,np.array([1,2,3,4]))  # 두 배열 더하기 가능

array([2, 4, 6, 8])

In [44]:
np.sum(ex)

10

In [45]:
np.cumsum(ex)

array([ 1,  3,  6, 10], dtype=int32)

In [46]:
np.mean(ex)

2.5

In [47]:
np.var(ex)

1.25

In [48]:
np.std(ex)

1.118033988749895

In [49]:
np.max(ex)

4

In [50]:
np.argmax(ex)

3

In [52]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [53]:
arr.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [54]:
arr.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [55]:
arr3d = np.arange(27).reshape(3,3,3)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [57]:
arr3d.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [59]:
arr3d.transpose(1,0,2)

array([[[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20]],

       [[ 3,  4,  5],
        [12, 13, 14],
        [21, 22, 23]],

       [[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26]]])